vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: /uploads/pictures
            upload_destination: '%kernel.project_dir%/public/uploads/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
